Seting up and developing my portfolio using HTMl CSS flexbox for mobi…
L2oukmane/Portfolio pull request #1
Opened 2022-01-05 14:45 UTC by L2oukmane

I have developed my personal portfolio for the mobile version using HTML, CSS, flexbox, and Linters for good code quality and bug detection.

2022-01-05 17:03 UTC, mmsesay requested changes
Hi @L2oukmane ,

Good job so far! 💪 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlight!
- Good PR ✔️
- Good commits ✔️
- Professional readme ✔️
- Code organization ✔️
- Styling ✔️

# Required Changes ♻️ ⛔️

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-05 17:03 UTC, mmsesay commented on index.html
> +        <div class="logo">My Logo</div>
- [ ] Good job working on this project. Site logos are elements that provide navigation back to homepages in websites.
Because of this reason, it will be nicer if we could swap the `h1` tag to an `a`.

2022-01-05 17:03 UTC, mmsesay commented on index.html
> +         <img class="onion"  src="/portfolioimgs/Union.svg" alt="navButton">
- [ ] You used the correct hamburger icon :+1: But am suggesting you wrap the `img` tag inside a `nav` tag because it will give it a more semantic meaning.

example:
```
  <nav>
      <img />
   </nav>
```

2022-01-05 17:03 UTC, mmsesay commented on index.html
> +    </main>
- [ ] Kudos in using a very good semantic tag here. But if we look closely, the container tag should be a section not a main. Since the portfolio project will comprise multiple sections, it will be more readable to use the section tag.
Please try to swap `main` tag for `section` tag

2022-01-05 17:03 UTC, mmsesay commented on style.css
> +  font-family: sans-serif;
- [ ] It seems you aren't using the correct fonts stated in your chosen template.
Keep in mind to also use the correct font sizing, margins etc. Just as given in the design.

2022-01-05 18:51 UTC, L2oukmane commented on style.css
> +  font-family: sans-serif;
Thank you for detecting the issues, I have fixed the ones mentioned I hope that I'm not missing something

2022-01-05 19:41 UTC, rotimiazeez requested changes
# Hi @L2oukmane 👋, 
### Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.🙄

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-05 19:41 UTC, rotimiazeez commented on index.html
> +        Glad to see you!</h2>
- [ ] Kindly make sure the page header uses an `h1` tag as it will be used by SEO(search engine optimizer) to find your page.✌

2022-01-05 19:41 UTC, rotimiazeez commented on index.html
> +</html>
- [ ] Please note that the links to the images and icons on your page are broken probably due to the changes made🤔.  Kindly rectify and fix this👍

2022-01-06 01:45 UTC, mike2611 approved these changes
Hi @L2oukmane , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-06 01:45 UTC, mike2611 commented on index.html
> +    </ul>
[OPTIONAL]

- [ ]  Please make your social media icons a little smaller and add some margin between them, to follow better the Figma Template
Your Project
![image](https://user-images.githubusercontent.com/28109626/148313973-f2487722-713a-4ae7-8f53-28e82e2aedbd.png)
Figma
![image](https://user-images.githubusercontent.com/28109626/148314019-c234e40b-a9b9-45d4-a174-94474ae1ac6a.png)

2022-01-06 06:53 UTC, merged